# Generated by Django 6.0.7 on 2026-07-10 11:24

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_bookings_options_alter_bookings_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredEvent',
            fields=[
            ],
            options={
                'verbose_name': 'Expired Event',
                'verbose_name_plural': 'Expired Event',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.event',),
        ),
        migrations.AlterModelOptions(
            name='bookings',
            options={},
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(default='no desc'),
            preserve_default=False,
        ),
    ]
